ecs_service_task_region                     = "us_east-1"
ecs_service_task_system_name                = "shokworks-task-definition"
ecs_service_task_ecr                        = "a"
ecs_service_task_deployment_env             = "dev"
ecs_service_task_cloudwatch_logs_group_name = "shokworks-backend"
